name: first workflow 
on:
  push:
   branches:
    - "main"

jobs:
  first-workflosw-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
   #  - name: before checkout action
    #   run: ls
     #  shell: bash

     - name: checkout step
       uses: actions/checkout@v4 
       
     - name: after checkout action
       run: ls 
       shell: bash 
       
     - name: run maven
       run: mvn clean package 
       shell: bash