name: first workflow 
on:
  push:
   branches:
    - "main"

jobs:
  first-workflosw-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
     - name: run bash command
       run: echo "first workflow"
       shell: bash